Initial skeleton changes
YosefLab/scvi-model-zoo pull request #3
Opened 2021-11-01 18:25 UTC by watiss

Tests still TBD, and so is the final API version, but sharing out what I have for a preliminary review.

2021-11-02 15:20 UTC, jjhong922 reviewed
Some initial comments, good work so far!

2021-11-02 15:20 UTC, jjhong922 commented on docs/conf.py
> +import scvimadz  # noqa
curious, what does madz stand for?

2021-11-02 15:20 UTC, jjhong922 commented on scvimadz/reference/_tabula_sapiens.py
> +    def __init__(self):
This should probably take a zenodo URL. If we end up supporting different storage options, we could allow for different storage identifier kwargs and assert that exactly one is provided.

2021-11-02 15:20 UTC, jjhong922 commented on scvimadz/reference/_tabula_sapiens.py
> +            if key.contains("tabula_sapiens")
Is the idea that the repo could potentially contain other things? I was thinking that the repo would be expected to be tabula sapiens specific already

2021-11-02 15:20 UTC, jjhong922 commented on scvimadz/reference/_tabula_sapiens.py
> +            self.load_model(model_key)
This will be really slow if we try to load them all during init, should wait until the user calls for a model specifically to load it.

2021-11-02 15:20 UTC, jjhong922 commented on scvimadz/storage/_zenodo.py
> +    def list_model_keys(self) -> List[str]:
I would avoid having the idea of a model and dataset even present in this class, and keep it to files and keys. Right now since theres the idea of a model and a dataset in both the reference and storage class, it's unclear what logic to put in each since there is no clear abstraction layer which could lead to it being messy later in the implementation.

2021-11-03 00:29 UTC, watiss commented on docs/conf.py
> +import scvimadz  # noqa
Model And Data Zoo :D

2021-11-03 00:35 UTC, watiss commented on scvimadz/reference/_tabula_sapiens.py
> +    def __init__(self):
I aimed to conceal the notion of storage behind the reference so users dont have to worry about providing that when instantiating a reference. But that also means that this TSReference is coupled with a Zenodo backend the way it's written. If we want a TSRefernece with a different backend, we can create a base TSReference and derive two child classes off of it each of which has their own backend.
We can also expose Storage at Reference creation time as you suggest. It isn't the design I went for but am open to exploring it. If we go with that, I'd prefer providing a Storage kwarg rather than a raw url string though.
Curious to know you guys' thoughts

2021-11-03 00:36 UTC, watiss commented on scvimadz/reference/_tabula_sapiens.py
> +            if key.contains("tabula_sapiens")
yes I was thinking that the repo could contain other pre-trained models, e.g. models pre-trained on other datasets.

2021-11-03 00:37 UTC, watiss commented on scvimadz/reference/_tabula_sapiens.py
> +            self.load_model(model_key)
Fair enough. I considered lazy loading but thought I might as well do it all at once. But if model loading is slow as you mention, that's not a good idea.

2021-11-03 00:37 UTC, watiss commented on scvimadz/storage/_zenodo.py
> +    def list_model_keys(self) -> List[str]:
Yeah that's a good call. I'll update.

2021-11-03 02:59 UTC, jjhong922 commented on scvimadz/reference/_tabula_sapiens.py
> +    def __init__(self):
Ah ok makes sense, didn't realize the plan was to hardcode the URL for this reference. That is fine for now I think. More general reference classes can offer a solution to this.

2021-11-22 19:13 UTC, jjhong922 reviewed
some nits and suggestions. feel free to ping me if you have questions on anything!

2021-11-22 19:13 UTC, jjhong922 commented on scvimadz/reference/base/_base_reference.py
> +        self._reference_prefix = self.reference_name + "_"  # e.g. tabula_sapiens_
also this is a little weird to me bc self.reference_name is an instance method and this is in the instance init method which means it could potentially fail if reference_name is defined as a function of an instance property. Alternatively you can just have a concrete instance method for this:

`def reference_prefix(self): return f"{self.reference_name}_"`

2021-11-22 19:13 UTC, jjhong922 commented on scvimadz/reference/base/_base_reference.py
> +        assert obj_type in ["model", "dataset"]
check and raise a ValueError here instead of an assert. Also, define {"model", "dataset"} as a constant set at the top of the file named `_OBJ_TYPES`.

2021-11-22 19:13 UTC, jjhong922 commented on scvimadz/reference/base/_base_reference.py
> +        store = self.model_store if obj_type == "model" else self.data_store
you can also define these constants individually since you use separately like here

2021-11-22 19:13 UTC, jjhong922 commented on scvimadz/reference/base/_base_reference.py
> +            rich_dataframe.prettify(
does this print to console or do you need to return it?

2021-11-22 19:13 UTC, jjhong922 commented on scvimadz/reference/base/_base_reference.py
> +            return df
reason not to return df in both cases?

2021-11-22 19:13 UTC, jjhong922 commented on scvimadz/reference/base/_base_reference.py
> +        return self._list_objects("model", "models_metadata.csv", pretty_print)
save these magic strings as constants since they are fixed file names

2021-11-22 19:13 UTC, jjhong922 commented on scvimadz/reference/base/_base_reference.py
> +        return self._list_objects("dataset", "datasets_metadata.csv", pretty_print)
same here

2021-11-22 19:13 UTC, jjhong922 commented on scvimadz/reference/base/_base_reference.py
> +        model_cls.load(os.path.dir_name(model_file), adata=adata, use_gpu=use_gpu)
do you need to return this?

2021-11-22 19:13 UTC, jjhong922 commented on scvimadz/reference/base/_base_reference.py
> +    def __init__(self) -> None:
for model_store and data_store I would add them as arguments here instead of creating abstract properties for them. Then call super().__init__() w/ them in each child class init

2021-11-22 19:13 UTC, jjhong922 commented on scvimadz/reference/_tabula_sapiens.py
> +        return "tabula_sapiens"
nit: you can just do `reference_name = "tabula_sapiens"` at the top of the class instead

2021-11-22 19:13 UTC, jjhong922 commented on scvimadz/storage/_zenodo.py
> +        self._zenodo_record_url = self._zenodo_base_url + "record/{}/files/{}"
nit: use f-strings here too

2021-11-22 19:13 UTC, jjhong922 commented on scvimadz/storage/_zenodo.py
> +        self._zenodo_record_url = self._zenodo_base_url + "record/{}/files/{}"
would name this `_zenodo_record_url_template` to explicit

2021-11-29 18:19 UTC, watiss commented on scvimadz/reference/base/_base_reference.py
> +    def __init__(self) -> None:
That's actually what I had in a prev iteration (might not have pushed it to GitHub). I ended up choosing this impl with abstract props instead in order to enforce subclassing BaseReference. That seems more in line with the pattern we have elsewhere...

2021-11-29 18:21 UTC, watiss commented on scvimadz/reference/_tabula_sapiens.py
> +        return "tabula_sapiens"
hmm, but I wanted to have abtract props (see other related comment). Can I do what you suggest while keeping that functionality?

2021-11-29 18:32 UTC, watiss commented on scvimadz/reference/base/_base_reference.py
> +        self._reference_prefix = self.reference_name + "_"  # e.g. tabula_sapiens_
Hmm I am not sure I follow. Why would this fail if `reference_name` is defined as a function of an instance property?

2021-11-29 18:33 UTC, watiss commented on scvimadz/reference/base/_base_reference.py
> +            return df
Oh good catch. Probably a leftover from a previous test I was doing.

2021-11-29 18:33 UTC, watiss commented on scvimadz/reference/base/_base_reference.py
> +            rich_dataframe.prettify(
yep it prints

2021-11-29 18:34 UTC, watiss commented on scvimadz/reference/base/_base_reference.py
> +        model_cls.load(os.path.dir_name(model_file), adata=adata, use_gpu=use_gpu)
I indeed do :D Good catch. (still testing this method)

2021-11-29 18:46 UTC, jjhong922 commented on scvimadz/reference/base/_base_reference.py
> +        self._reference_prefix = self.reference_name + "_"  # e.g. tabula_sapiens_
reference_name is an instance method, which means the developer is free to make it a function of anything relative to `self`. So a natural thing to do would be adding a reference_name argument to the init statement and then assigning that to `self._reference_name` and having the method return that. However, if you do that, this prefix thing will error because prior to assigning that variable, `self.reference_name` will be None.

2021-11-29 18:48 UTC, jjhong922 commented on scvimadz/reference/base/_base_reference.py
> +        self._reference_prefix = self.reference_name + "_"  # e.g. tabula_sapiens_
```
class Example(BaseReference):
  def __init__(self, ref_name):
    super().__init__()
    self._reference_name = ref_name

  @property
  def reference_name(self):
    return self._reference_name

e = Example() # errors in __init__ bc you cannot do None + "_"
```

2021-11-29 18:56 UTC, jjhong922 commented on scvimadz/reference/base/_base_reference.py
> +    def __init__(self) -> None:
We can still have the properties but just put them into the BaseReference class. By adding them as args to the BaseReference init method it'll still enforce child classes to pass a model and data store in. Since it's an abstract class, subclassing is always required.

2021-11-30 19:41 UTC, watiss commented on scvimadz/reference/base/_base_reference.py
> +    def __init__(self) -> None:
Talked offline. We would still need the abstract methods to enforce subclassing (merely inheriting from ABC does not suffice).

2021-11-30 19:42 UTC, watiss commented on scvimadz/storage/_zenodo.py
> +        self._zenodo_record_url = self._zenodo_base_url + "record/{}/files/{}"
I switched to using f-strings for the vars below this line but for `_zenodo_record_url` I could not use f-strings since it would complain about the other two missing placeholders (please let me know if there is a better way to do it, I was just doing: `f"{self._zenodo_base_url}record/{}/files/{}"`).

2021-11-30 19:45 UTC, watiss commented on scvimadz/reference/base/_base_reference.py
> +        self._reference_prefix = self.reference_name + "_"  # e.g. tabula_sapiens_
Talked offline. I was counting on `super().__init__()` being called at the end of the child init method in order to avoid these issues. But it looks like the common Python pattern is to call super init at the beginning, which could break things. I'll try the suggestion above.

2021-11-30 20:24 UTC, jjhong922 commented on scvimadz/storage/_zenodo.py
> +        self._zenodo_record_url = self._zenodo_base_url + "record/{}/files/{}"
oh yea for templates f strings require double brackets like this:
f"{self._zenodo_base_url}record/{{}}/files/{{}}"
then it resolves to single brackets

2021-12-06 17:53 UTC, adamgayoso requested changes
are we still on track to use this API to put models onto storage?

2021-12-06 17:53 UTC, adamgayoso commented on scvimadz/reference/base/_base_reference.py
> +        """ The backend store for datasets """
we should add codacy to this repo if it's not there already. This shouldn't have spaces around and should have a period

2021-12-06 17:53 UTC, adamgayoso commented on tests/test_references.py
> +    model = TabulaSapiens()
is there a way we can test this thing with zenodo? Probably not, right? We could write a `LocalStorage` class in the next pr to get some local testing ?

2021-12-09 07:27 UTC, watiss commented on tests/test_references.py
> +    model = TabulaSapiens()
I've added some network tests. I think a `LocalStorage` might be a good idea as well. I will look into it, if not in this PR in the next where I will implement `save`.

2021-12-09 07:27 UTC, watiss commented
> are we still on track to use this API to put models onto storage?

Yes

2021-12-27 19:13 UTC, watiss commented on scvimadz/_utils.py
> +def dirname(path: str) -> str:
Last time I tried that, it did not work for me.. but let me try again.

2022-01-02 21:19 UTC, watiss commented on scvimadz/_utils.py
> +def dirname(path: str) -> str:
It works! I deleted _utils.py

2022-01-03 19:28 UTC, jjhong922 reviewed
Few minor comments, looks good to move onto creating an API for uploading a model/dataset

2022-01-03 19:28 UTC, jjhong922 commented on pyproject.toml
> +]
nit: newline

2022-01-03 19:28 UTC, jjhong922 commented on scvimadz/reference/base/_base_reference.py
> +        if obj_type not in [_OBJ_TYPE_MODEL, _OBJ_TYPE_DATASET]:
If this string is only limited to two strings, you should explore using enums: https://docs.python.org/3/library/enum.html.

2022-01-03 19:28 UTC, jjhong922 commented on scvimadz/reference/base/_base_reference.py
> +        data_file = self.data_store.download_file(dataset_id)
Is the return here a filepath? If so it would make more sense to call this data_filepath

2022-01-03 19:28 UTC, jjhong922 commented on scvimadz/storage/_zenodo.py
> +    def download_file(self, key: str) -> str:
What is key vs id here?

2022-01-03 19:28 UTC, jjhong922 commented on scvimadz/storage/base/_base_storage.py
> +class BaseStorage(ABC):
Can you add a docstring describing the role of a Storage class and what keys are?

2022-01-03 19:28 UTC, jjhong922 commented on tests/mock/models/models_metadata.csv
> +hca_model_80262d08-4a30-4071-a3c6-96274182646d.zip,scvi.model.SCVI,0.5,0.9,Yes,hca_dataset_dcfaad7a-70a4-4669-87d2-7bb241673097.h5ad
do we expect to have .zip in the key?

2022-01-05 22:11 UTC, watiss commented on tests/mock/models/models_metadata.csv
> +hca_model_80262d08-4a30-4071-a3c6-96274182646d.zip,scvi.model.SCVI,0.5,0.9,Yes,hca_dataset_dcfaad7a-70a4-4669-87d2-7bb241673097.h5ad
Yes that's the scheme I've been using so far

2022-01-05 22:14 UTC, watiss commented on scvimadz/storage/_zenodo.py
> +    def download_file(self, key: str) -> str:
They're the same thing, I fixed the comment

2022-01-05 22:27 UTC, watiss commented on scvimadz/reference/base/_base_reference.py
> +        if obj_type not in [_OBJ_TYPE_MODEL, _OBJ_TYPE_DATASET]:
Do you mean something like:
```
class ObjType(Enum):
...     MODEL = "model"
...     DATASET = "dataset"
```
?
What is the benefit of that?

2022-01-05 22:28 UTC, watiss commented on scvimadz/reference/base/_base_reference.py
> +        data_file = self.data_store.download_file(dataset_id)
yes filepath

2022-01-05 22:50 UTC, jjhong922 commented on scvimadz/reference/base/_base_reference.py
> +        if obj_type not in [_OBJ_TYPE_MODEL, _OBJ_TYPE_DATASET]:
It allows you to type the obj_type argument insteading of having it as an arbitrary string type. It is more clear from the signature that it can only be two values rather than any string

2022-01-06 17:55 UTC, adamgayoso requested changes

2022-01-06 17:55 UTC, adamgayoso commented on scvimadz/reference/base/_base_reference.py
> +    def list_models(self, pretty_print: bool = False) -> pd.DataFrame:
```suggestion
    def get_models_df(self, pretty_print: bool = False) -> pd.DataFrame:
```
list to me seems like it would return a list

2022-01-06 17:55 UTC, adamgayoso commented on scvimadz/reference/base/_base_reference.py
> +            adata = self.load_dataset(model_adata)
would be nice to have a comment here

2022-01-06 17:55 UTC, adamgayoso commented on tests/mock/_mock_storage.py
> +    def __init__(self, data_type: str, save_path: str) -> None:
you can use the Literal type we define in scvi for data_type

2022-01-06 17:55 UTC, adamgayoso commented on tests/mock/models/models_metadata.csv
> +tabula_sapiens_model_bfeb6529-8db7-46ce-99f6-237748798ae4.zip,scvi.model.TOTALVI,0.3,0.8,No,tabula_sapiens_dataset_b4c16899-e458-4cf5-947e-bed59031f156.h5ad
I don't think we should add these binary files to the repo.... It will bloat the cloning. I was thinking the MockStorage testing would involve the save model functionality, so it's all sort of done on the fly during testing. Or, the data we use here has to be trivially small. Will need to edit the git history to remove these files

2022-01-06 17:55 UTC, adamgayoso commented on tests/mock/models/models_metadata.csv
> +hca_model_80262d08-4a30-4071-a3c6-96274182646d.zip,scvi.model.SCVI,0.5,0.9,Yes,hca_dataset_dcfaad7a-70a4-4669-87d2-7bb241673097.h5ad
can you explain the concern? @jjhong922

2022-01-06 19:14 UTC, jjhong922 commented on tests/mock/models/models_metadata.csv
> +hca_model_80262d08-4a30-4071-a3c6-96274182646d.zip,scvi.model.SCVI,0.5,0.9,Yes,hca_dataset_dcfaad7a-70a4-4669-87d2-7bb241673097.h5ad
Just thinking that the ID should be separated from the idea of a filepath. For example if we have unzipped or differently compressed versions of a model, we should be able to append a file type ending to the ID rather than stripping the .zip everytime.

2022-01-10 20:49 UTC, watiss commented on tests/mock/_mock_storage.py
> +    def __init__(self, data_type: str, save_path: str) -> None:
I think the use of Enum class, as Justin suggested in another comment, obviates the need for this

2022-01-10 21:57 UTC, watiss commented on tests/mock/models/models_metadata.csv
> +tabula_sapiens_model_bfeb6529-8db7-46ce-99f6-237748798ae4.zip,scvi.model.TOTALVI,0.3,0.8,No,tabula_sapiens_dataset_b4c16899-e458-4cf5-947e-bed59031f156.h5ad
I went with the second option to avoid network traffic. Network roundtrips take a while anyway for large files so we'd anyway have to cut down on the size. We might as well avoid the traffic altogether and keep the small files locally. I cut both datasets down to 50-100 cells and same number of vars (of course they're meaningless now but it's ok for our purposes).
I'll add in a LocalStorage class, peer to ZenodoStorage in the next pr when I add in save functionality

2022-01-10 21:57 UTC, watiss commented on scvimadz/reference/base/_base_reference.py
> +    def list_models(self, pretty_print: bool = False) -> pd.DataFrame:
updated

2022-01-17 17:45 UTC, watiss commented
@adamgayoso Could you take another pass?

2022-01-19 18:53 UTC, adamgayoso approved these changes

2022-01-24 18:28 UTC, merged